  version: '3'

  services:
    db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres

    bm_service:
      build: .
      command: bash docker-entrypoint.sh
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

    async_bm_service:
      build: async_BM_service
      command: python async_service.py
      volumes:
        - ./async_BM_service:/code
      depends_on:
        - bm_service