# Generated by Django 3.0.7 on 2020-06-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('api_key', models.CharField(max_length=24)),
                ('api_secret', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('symbol', models.CharField(max_length=10)),
                ('volume', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('side', models.CharField(choices=[('B', 'Buy'), ('S', 'Sell')], default='B', max_length=1)),
                ('price', models.DecimalField(decimal_places=12, max_digits=24)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
    ]
